name: page
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
     sdk: flutter
  jaspr: ^0.21.6
  jaspr_flutter_embed: ^0.4.9
  jaspr_router: ^0.7.3

dev_dependencies:
  build_runner: ^2.6.0
  jaspr_web_compilers: ^4.2.3+1
  jaspr_builder: ^0.21.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  jaspr_lints: ^0.5.1

jaspr:
  mode: static

flutter:
  uses-material-design: true
